const PICKER_ES = {
  // Sections
  __section_bedroom: "Dormitorio",
  __section_bathroom: "Baño",
  __section_vanity: "Tocador",
  __section_general: "General",
  // General subgroup labels (group letters)
  __general_group_a: "Sala / Patio / Calentador",
  __general_group_b: "Refri / Microondas / Pasillo",
  __general_group_c: "Ventilas / Estufa / Horno / Lavavajillas",
  __general_group_d: "Cocina",
  // General subcategory items
  "general:living_room": "Sala",
  "general:patio": "Patio",
  "general:water_heater": "Calentador de agua",
  "general:hallways": "Pasillo",
  "general:refrigerator": "Refrigerador",
  "general:freezer": "Congelador",
  "general:microwave": "Microondas",
  "general:breezeway": "Pasillo exterior",
  "general:vents": "Ventilas",
  "general:stove": "Estufa",
  "general:oven": "Horno",
  "general:dishwasher": "Lavavajillas",
  "general:kitchen": "Cocina",
  // Common Bedroom items (best-effort — extend as the team adds more)
  "bedroom:bed": "Cama",
  "bedroom:nightstand": "Mesa de noche",
  "bedroom:dresser": "Cómoda",
  "bedroom:mirror": "Espejo",
  "bedroom:closet": "Clóset",
  "bedroom:windows": "Ventanas",
  "bedroom:blinds": "Persianas",
  "bedroom:floor": "Piso",
  "bedroom:baseboards": "Zócalos",
  "bedroom:fan": "Ventilador",
  "bedroom:light_fixture": "Lámpara",
  "bedroom:outlets": "Tomacorrientes",
  "bedroom:doors": "Puertas",
  "bedroom:walls": "Paredes",
  // Common Bathroom items
  "bathroom:toilet": "Inodoro",
  "bathroom:shower": "Ducha",
  "bathroom:tub": "Tina",
  "bathroom:sink": "Lavabo",
  "bathroom:mirror": "Espejo",
  "bathroom:floor": "Piso",
  "bathroom:walls": "Paredes",
  "bathroom:vent": "Ventila",
  "bathroom:cabinets": "Gabinetes",
  // Common Vanity items
  "vanity:counter": "Mesón",
  "vanity:sink": "Lavabo",
  "vanity:faucet": "Grifo",
  "vanity:mirror": "Espejo",
  "vanity:cabinets": "Gabinetes",
  "vanity:floor": "Piso",
  // Common request keys
  "requested:extra_item": "Tarea adicional",
};

// Resolve a label for an item key in the current locale.
// Lookup order: override > dictionary > humanized English fallback.
// English display labels for template item keys, keyed by
// `${section}:${item_key}`. Sourced from section_template_items so the
// app shows the clean stored label (e.g. 'Breezeway sweep') instead of
// a humanized key ('Bw sweep'). Falls through to humanize for any key
// not listed here.
const PICKER_EN = {
  "general:sink_short": "Sink",
  "general:faucet_short": "Faucet",
  "general:under_sink": "Under sink",
  "general:counter_tops": "Counter tops",
  "general:cupboards_oiled": "Cupboards oiled",
  "general:drawers_oiled": "Drawers oiled",
  "general:kitchen_floor": "Kitchen floor",
  "general:table_chairs_short": "Table/chairs",
  "general:kitchen_walls_short": "Walls",
  "general:baseboards": "Baseboards",
  "general:lt_switches": "Light switches",
  "general:lt_fixtures": "Light fixtures",
  "general:trash": "Trash",
  "vanity:sink": "Sink",
  "vanity:faucet": "Faucet",
  "vanity:counter": "Counter",
  "vanity:mirror": "Mirror",
  "vanity:lt_switch": "Light switch",
  "vanity:walls": "Walls",
  "vanity:floor": "Floor",
  "vanity:baseboard": "Baseboard",
  "vanity:door_knob": "Door knob",
  "bathroom:tub": "Tub",
  "bathroom:faucet": "Faucet",
  "bathroom:tub_walls": "Tub walls",
  "bathroom:walls_above_tub": "Walls above tub",
  "bathroom:door_knob": "Door knobs",
  "bathroom:light_fixtures": "Light fixtures",
  "bathroom:lt_switch": "Light switches",
  "bedroom:vacuum_entire": "Vacuum",
  "bedroom:dust": "Dust",
  "bedroom:lt_switch": "Light switch",
  "bedroom:dr_knob": "Door knob",
  "bedroom:top_df_ct": "Top of door frame & closet trim",
  "bedroom:window_blinds": "Blinds",
  "bedroom:window_track": "Window track",
  "bedroom:window_sill": "Window sill",
  "bedroom:window_walls": "Window walls",
  "bedroom:baseboard": "Baseboard",
  "general:lrm_vac": "LRM vac",
  "general:hw_mop_vac": "HW mop/vac",
  "general:lrm_hw_bb": "LRM/HW baseboards",
  "general:lrm_hw_walls": "LRM/HW walls",
  "general:dust_furniture": "Dust furniture",
  "general:lamp_shades": "Lamp/shades",
  "general:under_cushions": "Under cushions",
  "general:blinds": "Blinds",
  "general:patio_door": "Patio door",
  "general:track": "Track",
  "general:patio_walls": "Patio walls",
  "general:patio_floor": "Patio floor",
  "general:top_water_heater": "Top of water heater",
  "general:heater_closet_floor": "Heater closet floor",
  "general:stove_top_short": "Stove top",
  "general:hood": "Hood",
  "general:under_burners": "Under burners",
  "general:rings_spill_pan": "Rings/spill pan",
  "general:oven_inside_short": "Oven inside",
  "general:oven_outside": "Oven outside",
  "general:oven_handle": "Oven handle",
  "general:drawer_handle": "Drawer handle",
  "general:drawer": "Drawer",
  "general:dishwasher_inside": "Dishwasher inside",
  "general:dishwasher_outside": "Dishwasher outside",
  "general:vents_4": "Vents in hallway (4)",
  "bathroom:toilet_ring": "Toilet/ring",
  "bathroom:fan_vent": "Fan vent",
  "bathroom:walls": "Walls",
  "bathroom:baseboard": "Baseboard",
  "bathroom:floor": "Floor",
  "bathroom:ceiling_mold": "Ceiling mold",
  "general:fridge_top": "Fridge outside/top",
  "general:fridge_drawers": "Fridge inside/drawers",
  "general:fridge_gasket": "Fridge rubber gasket",
  "general:freezer_inside": "Freezer inside",
  "general:freezer_gasket": "Freezer rubber gasket",
  "general:microwave_short": "Microwave",
  "general:bw_sweep": "Breezeway sweep",
  "general:bw_vacuum": "Breezeway vacuum",
  "general:bw_walls": "Breezeway walls",
  "general:fd_inside": "Front door inside",
  "general:fd_outside": "Front door outside",
  "general:doorbell": "Doorbell",
  "general:bw_ceiling": "Breezeway ceiling around front door",
  "general:front_room_closet": "Front room closet",
};

export function resolveItemLabel(key, locale, overrides, englishFallback) {
  if (overrides && overrides.has(key)) return overrides.get(key);
  if (locale === "es" && PICKER_ES[key]) return PICKER_ES[key];
  if (PICKER_EN[key]) return PICKER_EN[key];
  return englishFallback;
}
